# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docked_pyrometer_control.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_docked_pyro_controls(object):
    def setupUi(self, docked_pyro_controls):
        docked_pyro_controls.setObjectName("docked_pyro_controls")
        docked_pyro_controls.resize(700, 285)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(docked_pyro_controls.sizePolicy().hasHeightForWidth())
        docked_pyro_controls.setSizePolicy(sizePolicy)
        docked_pyro_controls.setMinimumSize(QtCore.QSize(700, 285))
        font = QtGui.QFont()
        font.setPointSize(10)
        docked_pyro_controls.setFont(font)
        docked_pyro_controls.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        docked_pyro_controls.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gbox_current_pyro_temp = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.gbox_current_pyro_temp.setObjectName("gbox_current_pyro_temp")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gbox_current_pyro_temp)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_current_pyro_temp = QtWidgets.QLabel(self.gbox_current_pyro_temp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_current_pyro_temp.sizePolicy().hasHeightForWidth())
        self.lbl_current_pyro_temp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_current_pyro_temp.setFont(font)
        self.lbl_current_pyro_temp.setAutoFillBackground(False)
        self.lbl_current_pyro_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_current_pyro_temp.setObjectName("lbl_current_pyro_temp")
        self.horizontalLayout_2.addWidget(self.lbl_current_pyro_temp)
        self.verticalLayout_3.addWidget(self.gbox_current_pyro_temp)
        self.gbox_pyro_logging_setup = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.gbox_pyro_logging_setup.setObjectName("gbox_pyro_logging_setup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbox_pyro_logging_setup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_log_interval = QtWidgets.QLabel(self.gbox_pyro_logging_setup)
        self.lbl_log_interval.setObjectName("lbl_log_interval")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_log_interval)
        self.ln_log_interval = QtWidgets.QLineEdit(self.gbox_pyro_logging_setup)
        self.ln_log_interval.setMinimumSize(QtCore.QSize(0, 28))
        self.ln_log_interval.setObjectName("ln_log_interval")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ln_log_interval)
        self.lbl_pyro_slope = QtWidgets.QLabel(self.gbox_pyro_logging_setup)
        self.lbl_pyro_slope.setObjectName("lbl_pyro_slope")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_pyro_slope)
        self.ln_pyro_slope = QtWidgets.QLineEdit(self.gbox_pyro_logging_setup)
        self.ln_pyro_slope.setMinimumSize(QtCore.QSize(0, 28))
        self.ln_pyro_slope.setObjectName("ln_pyro_slope")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ln_pyro_slope)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_pyro_log_file = QtWidgets.QLabel(self.gbox_pyro_logging_setup)
        self.lbl_pyro_log_file.setObjectName("lbl_pyro_log_file")
        self.horizontalLayout.addWidget(self.lbl_pyro_log_file)
        self.ln_pyro_log_file = QtWidgets.QLineEdit(self.gbox_pyro_logging_setup)
        self.ln_pyro_log_file.setMinimumSize(QtCore.QSize(0, 28))
        self.ln_pyro_log_file.setObjectName("ln_pyro_log_file")
        self.horizontalLayout.addWidget(self.ln_pyro_log_file)
        self.btn_pyro_log_file = QtWidgets.QPushButton(self.gbox_pyro_logging_setup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pyro_log_file.sizePolicy().hasHeightForWidth())
        self.btn_pyro_log_file.setSizePolicy(sizePolicy)
        self.btn_pyro_log_file.setMinimumSize(QtCore.QSize(0, 28))
        self.btn_pyro_log_file.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_pyro_log_file.setObjectName("btn_pyro_log_file")
        self.horizontalLayout.addWidget(self.btn_pyro_log_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.btn_pyro_log_start_stop = QtWidgets.QPushButton(self.gbox_pyro_logging_setup)
        self.btn_pyro_log_start_stop.setMinimumSize(QtCore.QSize(0, 28))
        self.btn_pyro_log_start_stop.setObjectName("btn_pyro_log_start_stop")
        self.verticalLayout_2.addWidget(self.btn_pyro_log_start_stop)
        self.verticalLayout_3.addWidget(self.gbox_pyro_logging_setup)
        self.verticalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gbox_pyro_live_video = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.gbox_pyro_live_video.setObjectName("gbox_pyro_live_video")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbox_pyro_live_video)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_pyro_live_video = QtWidgets.QLabel(self.gbox_pyro_live_video)
        self.lbl_pyro_live_video.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_pyro_live_video.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pyro_live_video.setObjectName("lbl_pyro_live_video")
        self.verticalLayout.addWidget(self.lbl_pyro_live_video)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_enable_video = QtWidgets.QCheckBox(self.gbox_pyro_live_video)
        self.check_enable_video.setMinimumSize(QtCore.QSize(0, 28))
        self.check_enable_video.setObjectName("check_enable_video")
        self.horizontalLayout_4.addWidget(self.check_enable_video)
        self.btn_get_frame = QtWidgets.QPushButton(self.gbox_pyro_live_video)
        self.btn_get_frame.setMinimumSize(QtCore.QSize(0, 28))
        self.btn_get_frame.setObjectName("btn_get_frame")
        self.horizontalLayout_4.addWidget(self.btn_get_frame)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_3.addWidget(self.gbox_pyro_live_video)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 3)
        docked_pyro_controls.setWidget(self.dockWidgetContents)

        self.retranslateUi(docked_pyro_controls)
        QtCore.QMetaObject.connectSlotsByName(docked_pyro_controls)

    def retranslateUi(self, docked_pyro_controls):
        _translate = QtCore.QCoreApplication.translate
        docked_pyro_controls.setWindowTitle(_translate("docked_pyro_controls", "Pyrometer Controls"))
        self.gbox_current_pyro_temp.setTitle(_translate("docked_pyro_controls", "Current Temperature"))
        self.lbl_current_pyro_temp.setText(_translate("docked_pyro_controls", "TextLabel"))
        self.gbox_pyro_logging_setup.setTitle(_translate("docked_pyro_controls", "Logging Setup"))
        self.lbl_log_interval.setText(_translate("docked_pyro_controls", "Log Interval (s):"))
        self.lbl_pyro_slope.setText(_translate("docked_pyro_controls", "Pyrometer Slope:"))
        self.lbl_pyro_log_file.setText(_translate("docked_pyro_controls", "Log File:"))
        self.btn_pyro_log_file.setText(_translate("docked_pyro_controls", "..."))
        self.btn_pyro_log_start_stop.setText(_translate("docked_pyro_controls", "Start Logging"))
        self.gbox_pyro_live_video.setTitle(_translate("docked_pyro_controls", "Pyrometer Camera Live View"))
        self.lbl_pyro_live_video.setText(_translate("docked_pyro_controls", "Live Video"))
        self.check_enable_video.setText(_translate("docked_pyro_controls", "Enable Live Video"))
        self.btn_get_frame.setText(_translate("docked_pyro_controls", "Get Video Frame"))

